### ISSUE TITLE
Error on initial render

### ISSUE THREAD

**Issue by I-keep-trying** [encoreshao/react-google-login#1]
I don't think this is a problem with your app, obviously your demo works fine, so I'm just trying to get it working for me.

I cloned this repo, added my own google client ID both places (which I have used successfully in other apps on localhost, so I think the app is configured correctly in the google api console)  but I get this error _instead_ of the login button: 

```
{"error":"idpiframe_initialization_failed",
"details":"You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."}
```

This makes no sense, since this is supposed to be a demo of the _new_ GIS api, right?

When I dismiss the error, I get the login button, but when I click on it, a popup opens with a 'loading' circle, but it closes itself and I get another error:

```
{"error":"popup_closed_by_user"}
```

Any ideas how to troubleshoot this?

**Comment by encoreshao** [comment]
hey @I-keep-trying,

I've never encountered this error before, try to google this error and find a [related article](
https://www.anycodings.com/questions/how-to-solve-idpiframeinitializationfailed-for-localhost), maybe you can try if it can solve your problem.

I am not sure about your credentials in google. 'd like to share my credentials with you, pls make sure to add the correct origins from your google console.

<img width="660" alt="Screen Shot 2022-08-10 at 16 12 54" src="https://user-images.githubusercontent.com/745929/183850788-f4d5385f-0100-442e-a27e-564c105f2114.png">

Hope it helps to you!

**Comment by I-keep-trying** [comment]
Thanks for the quick response. 

I checked, and I have the same config in my console, localhost as well as my published app link. 

I have, for now anyway, given up on the google login. It's just too difficult to work with, for me. I can't even copy a working example and get it to work. :-( 

So I'll just stick to regular old username/pw forms, with jwt and http-only cookies.
